-- MySQL 8+ schema is generated by SQLAlchemy migrations in production.
-- This bootstrap remains useful for DBAs and schema review.
CREATE DATABASE IF NOT EXISTS tpems CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tpems;
-- Run `python seed.py` after application startup to create normalized tables.
